name = "Drifting-PaperMod"
license = "MIT"
licenselink = "https://github.com/DriftingBoats/Drifting-PaperMod/blob/main/LICENSE"
description = "A personalized Hugo PaperMod fork used by Drifting Boats."
homepage = "https://github.com/DriftingBoats/Drifting-PaperMod"
demosite = "https://blog.drifting.boats/"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "search",
  "papermod"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.146.0"

[author]
  name = "DriftingBoats"
  homepage = "https://github.com/DriftingBoats"

[original]
  name = "hugo-PaperMod"
  author = "Aditya Telange"
  homepage = "https://github.com/adityatelange"
  repo = "https://github.com/adityatelange/hugo-PaperMod"